#80表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80

spring:
  application:
    #服务别名----注册zookeeper到注册中心名称
    name: cloud-consumer-order

  cloud:
    zookeeper:
      #window连接虚拟机的地址，最后一个是zookeeper的端口号
      connect-string: 192.168.17.131:2181



